### ISSUE TITLE
loading 转圈bug

### ISSUE THREAD

**Issue by geektcp** [KuangPF/dumi-theme-antd#10]
引用dumi-theme-antd，
启动后，点击任意链接，然后再点击左上角回到首页时，
此时首页右上角一直在loading 转圈。

------------------------
试过四五个版本，几乎所有版本都存在此问题，包括目前最新版本0.2.7

**Comment by geektcp** [comment]
问题已经查出，复现条件如下：
docs目录只有文件夹和文件夹里面的md文档，docs不存在index.md文件，就会出现。

------------
解决方案：
1、补充index.md文件到docs目录下。
2、建议主题代码增强健壮性。

**Comment by KuangPF** [comment]
问题我大致看了，如果涉及到自定义页面，比如 `page/xxx.tsx`，因为首页是完全自定义的，nprocess 就会复现 bug，如果是 md 则不会，这点我和官方确定下具体问题原因，antd5 官网一样也存在这个 bug。

**Comment by geektcp** [comment]
> 问题我大致看了，如果涉及到自定义页面，比如 `page/xxx.tsx`，因为首页是完全自定义的，nprocess 就会复现 bug，如果是 md 则不会，这点我和官方确定下具体问题原因，antd5 官网一样也存在这个 bug。

没错antd官网也有这问题， nprogress 把这个参数设置为false，也可以避免转圈。先解决下问题。

**Comment by KuangPF** [comment]
官方已解决该问题，升级主题包至0.2.13即可解决。
