### ISSUE TITLE
body污染的 全局样式

### ISSUE THREAD

**Issue by chico-malo** [KuangPF/dumi-theme-antd#12]
环境：
- "dumi": "^2.2.1"
- "dumi-theme-antd": "^0.2.7"

去掉dumi-theme-antd 主题，一切正常。所以判断问题出在了主题中。

问题1：
![image](https://github.com/KuangPF/dumi-theme-antd/assets/26463204/ed78ef49-c6cc-4ba1-86a7-a3538983ba8f)

body全局样式会被一个叫 Common.tsx 覆盖掉。

问题2：
在某些场景，Common.tsx 的样式，再次被覆盖。
![image](https://github.com/KuangPF/dumi-theme-antd/assets/26463204/96c44047-5f0b-4f8d-8fd7-77c2f2a24c4d)

Sample Code
无
demo地址：https://assets-test.sto.cn/ux/cn-eone/0.0.1-alpha.5/guide/index.html

**Comment by KuangPF** [comment]
Common.tsx 是基于`@emotion/react` 定义的 body 默认样式，试了下官网的[样式覆盖](https://d.umijs.org/guide/project-structure#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F)，貌似并没有生效，而且文档打包以后会直接插入到 style 标签中。目前来看并没有比较合适的解决办法，建议通过 css 选择器的权重或者层级自定义覆盖吧。

**Comment by KuangPF** [comment]
增加了钉钉群，可以加下，后期有问题可以快速了解解答。
<img width=300 src="https://github.com/KuangPF/dumi-theme-antd/assets/20694238/3aa88f29-0995-4452-8b07-5a46cc522b77">

**Comment by chico-malo** [comment]
> Common.tsx 是基于`@emotion/react` 定义的 body 默认样式，试了下官网的[样式覆盖](https://d.umijs.org/guide/project-structure#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F)，貌似并没有生效，而且文档打包以后会直接插入到 style 标签中。目前来看并没有比较合适的解决办法，建议通过 css 选择器的权重或者层级自定义覆盖吧。

图1的body可以使用权重覆盖。
但是图2的默认样式，有点恶心了… 这个能修复嘛

**Comment by KuangPF** [comment]
图2是 antd 组件的默认样式，antd 包里面，不好改。
