### ISSUE TITLE
控制台报错 colorItemBg 废弃

### ISSUE THREAD

**Issue by consistent-k** [KuangPF/dumi-theme-antd#19]
![image](https://github.com/KuangPF/dumi-theme-antd/assets/67736912/a38cbbe1-1fde-431b-9130-0ed0f7771898)

请替换后发版

**Comment by KuangPF** [comment]
使用的 antd 版本是多少

**Comment by consistent-k** [comment]
> 使用的 antd 版本是多少

5.7.2

**Comment by KuangPF** [comment]
嗯，是由于版本号兼容的问题造成，已修复，下次发版生效。

**Comment by KuangPF** [comment]
0.2.13 已修复
