### ISSUE TITLE
首页按钮和导航不支持跳转外链

### ISSUE THREAD

**Issue by Nan-Mo** [KuangPF/dumi-theme-antd#2]

**Comment by KuangPF** [comment]
已做支持 [237a723](https://github.com/KuangPF/dumi-theme-antd/commit/237a723f08ff587a635ebc13d78b38a265dbefe0)

**Comment by KuangPF** [comment]
[0.2.1](https://github.com/KuangPF/dumi-theme-antd/releases/tag/0.2.1)版本已支持。
