### ISSUE TITLE
安装依赖警告问题

### ISSUE THREAD

**Issue by consistent-k** [KuangPF/dumi-theme-antd#25]
项目里使用的antd版本是5.9.0，会报以下警告。
技术栈：pnpm8、antd5.9.0 、dumi2、dumi-theme-antd@latest
![image](https://github.com/KuangPF/dumi-theme-antd/assets/67736912/ae3b41a2-c632-4023-aa1f-c4eb6ed16fa1)

**Comment by KuangPF** [comment]
这个影响不大，主要是一个版本号的兼容范围问题，antd 次版本以及补丁版本都会向下兼容。
