### ISSUE TITLE
themeConfig的nav配置children无效

### ISSUE THREAD

**Issue by 39Nyx** [KuangPF/dumi-theme-antd#30]
例如如下配置
```typescript
export default defineConfig({
  themeConfig: {
    nav: [
      {
        title: '国内镜像',
        link: 'https://ant-design.antgroup.com/index-cn',
        children: [
          { title: '官方镜像', link: 'https://ant-design.antgroup.com/index-cn' },
          { title: 'Gitee 镜像', link: 'https://ant-design.antgroup.com/index-cn' }
        ]
      }
    ]
  }
});
```
期望结果
<img width="694" alt="a2" src="https://github.com/KuangPF/dumi-theme-antd/assets/131958057/b10080ba-1fa5-4bac-8b21-502cb1fcd7ff">

配置项
![a1](https://github.com/KuangPF/dumi-theme-antd/assets/131958057/f27ad805-d000-4c99-b01c-229bdfde0098)

**Comment by KuangPF** [comment]
感谢贡献，已更新版本 [0.3.14](https://github.com/KuangPF/dumi-theme-antd/releases/tag/0.3.14)。
