### ISSUE TITLE
header多页面tab样式混乱 and 能否支持一下 antd 组件页面的 ComponentMeta 

### ISSUE THREAD

**Issue by DWLingXiao** [KuangPF/dumi-theme-antd#36]
![image](https://github.com/user-attachments/assets/d7b95086-9561-4258-839d-b529143292b4)

**Comment by DWLingXiao** [comment]
![image](https://github.com/user-attachments/assets/0b61f9de-70e8-41cb-aac5-0a619389f9bb)
使用dumi的页面tab构建方法导致title和tab重叠

**Comment by KuangPF** [comment]
ComponentMeta 信息有点定制化了，建议在项目里面采用[基础组件](https://d.umijs.org/theme/global-component#%E5%9F%BA%E7%A1%80%E7%A4%BA%E4%BE%8B)的方式实现。

**Comment by KuangPF** [comment]
0.4.2 已调整 tab 样式
