### ISSUE TITLE
首页支持配置背景图片

### ISSUE THREAD

**Issue by jaijia-bao** [KuangPF/dumi-theme-antd#4]
现在的背景图片明显是antd 5.0的元素，希望可以支持替换；或者默认换成通用一点的图片，不要包含品牌元素

**Comment by KuangPF** [comment]
下次迭代支持上

**Comment by KuangPF** [comment]
[v0.2.3](https://github.com/KuangPF/dumi-theme-antd/releases/tag/0.2.3) 版本已支持。

**Comment by jaijia-bao** [comment]
@KuangPF 自适应有问题 因为高度固定，在缩放屏幕的时候 背景图会跟着缩放导致变形
