### ISSUE TITLE
markdown代码块显示行号

### ISSUE THREAD

**Issue by theFG1998** [KuangPF/dumi-theme-antd#5]
请问如何在markdown代码块中显示行号

**Comment by KuangPF** [comment]
dumi 官方不支持该特性，所以当前版本还展示不了行号。后续该插件迭代时考虑增加一个显示行号的特性。

**Comment by KuangPF** [comment]
PR 已合入，等待官方发布新版本。https://github.com/umijs/dumi/pull/1654

**Comment by theFG1998** [comment]
> PR 已合入，等待官方发布新版本。[umijs/dumi#1654](https://github.com/umijs/dumi/pull/1654)

Thank you sir~
