### ISSUE TITLE
cmd + k快速搜索定位失效

### ISSUE THREAD

**Issue by fe-noob** [KuangPF/dumi-theme-antd#6]
使用cmd+k快速搜索时，点击后hash更改了但是没有滑动到对应的锚点位置
https://kuangpf.com/dumi-theme-antd/ 也存在相同的问题

有空可以看看😂

**Comment by KuangPF** [comment]
[0.2.4](https://github.com/KuangPF/dumi-theme-antd/releases/tag/0.2.4)版本已修复。
