### ISSUE TITLE
0.2.5版本，新增的bannerConfig属性失效，导致mainContent dom丢失

### ISSUE THREAD

**Issue by chico-malo** [KuangPF/dumi-theme-antd#9]
嗨咯，这是更新版本后出现的问题，退回 0.2.4 一切正常。
demo截图：
![image](https://github.com/KuangPF/dumi-theme-antd/assets/26463204/6ca6c684-6ded-4f07-a2d3-d1bd272e7c56)
主题配置截图：
![image](https://github.com/KuangPF/dumi-theme-antd/assets/26463204/c49b89aa-8dfc-436e-8d7c-8c82175cc677)

**Comment by KuangPF** [comment]
* [bannerConfig](https://kuangpf.com/dumi-theme-antd/config/base#bannerconfig) 字段，不是 `bannerConfigDefault`
* 看下是不是自定义了首页 `pages/index `  ,`0.2.5`版本支持了首页自定义 [ChangeLog](https://kuangpf.com/dumi-theme-antd/guide/changelog#025)

**Comment by chico-malo** [comment]
> * [bannerConfig](https://kuangpf.com/dumi-theme-antd/config/base#bannerconfig) 字段，不是 `bannerConfigDefault`
> * 看下是不是自定义了首页 `pages/index `  ,`0.2.5`版本支持了首页自定义 [ChangeLog](https://kuangpf.com/dumi-theme-antd/guide/changelog#025)

啊，抱歉，我的问题，默认配置docs/index 这个导致的（删除正常了） 多谢。
